PLAD-82  As a student, I want to be able to see a list of placements that I matched with
Fabs97/PlaDat pull request #36
Opened 2020-12-09 11:09 UTC by AliceCasali

2020-12-09 11:49 UTC, Fabs97 requested changes

2020-12-09 11:49 UTC, Fabs97 commented on backend/routes/matchRoute.js
> +
I think this should have some error codes if anything fails.

2020-12-11 10:01 UTC, AnnaBergamasco commented on backend/docs/documentation.yaml
> +                        "employerName": "Google"
Related to the review for matchRoute.js, when adding error codes they should also be added as responses here

2020-12-11 14:49 UTC, Fabs97 approved these changes

2020-12-11 14:49 UTC, merged