PLAD-67 - As a user, I want to be able to log in, so that I have access to the system
Fabs97/PlaDat pull request #55
Opened 2021-01-09 09:18 UTC by Fabs97

2021-01-09 18:59 UTC, AliceCasali approved these changes
Everything seems correct from a frontend point of view, the app is running correctly (finallyyyyyy)

2021-01-09 22:26 UTC, AnnaBergamasco requested changes
Overall super good job!
Most of my comments are about missing error handling parts that aren't actually that vital, but there are also three TODOs left in the code.

2021-01-10 11:24 UTC, aidadenisa commented on backend/DAO/employerDAO.js
> +
added

2021-01-10 11:32 UTC, aidadenisa commented on backend/DAO/employerDAO.js
> +            .where('p.id', id);
added

2021-01-10 11:34 UTC, aidadenisa commented on backend/DAO/matchDAO.js
> +            .andWhere('shp.status', 'ACCEPTED')
added

2021-01-10 11:35 UTC, aidadenisa commented on backend/DAO/registrationDAO.js
> +            .where('email', email)
added

2021-01-10 11:36 UTC, aidadenisa commented on backend/DAO/studentDAO.js
> +
added

2021-01-10 11:37 UTC, aidadenisa commented on backend/DB/migrations/20210109014342_delete_phone_and_email_from_student.js
> +    let check2 = await knex.schema.hasColumn('student', "password");
fixed

2021-01-10 11:39 UTC, aidadenisa commented on backend/docs/documentation.yaml
> -                      "Trekking"
updated

2021-01-10 11:40 UTC, aidadenisa commented on backend/routes/matchRoute.js
> +    const choice = await matchService.saveChoice(req.body, req.user);
fixed

2021-01-10 11:40 UTC, aidadenisa commented on backend/routes/registrationRoute.js
> +    // TODO: allow only logged in users to delete themselves
implemented

2021-01-10 11:40 UTC, aidadenisa commented on backend/routes/studentRoute.js
> +    // TODO: THE userID variable should be the same as userID of the logged in user
implemented

2021-01-10 11:40 UTC, aidadenisa commented on backend/services/matchService.js
> +        //TODO: CHECK THAT IF THE ACCOUNT IS STUDENT, THE STUDENT_ACCEPT IS SET (equivalent for employer)
implemented

2021-01-10 11:40 UTC, aidadenisa commented on backend/services/middlewareService.js
> +        if(req.url === '/login' || req.url === '/registration' || /\/user\/[0-9]*$/.test(req.url)) {
fixed, very good catch!

2021-01-10 11:41 UTC, aidadenisa commented on backend/DAO/registrationDAO.js
> +            .del();
fixed

2021-01-10 11:41 UTC, aidadenisa commented on backend/services/registrationService.js
> +        return registrationDAO.deleteUserById(userId);
done

2021-01-10 11:41 UTC, aidadenisa commented on backend/services/studentService.js
> +        return studentDAO.getStudentByUserId(userId);
done

2021-01-10 15:40 UTC, AnnaBergamasco approved these changes

2021-01-10 17:28 UTC, AliceCasali approved these changes

2021-01-10 17:32 UTC, merged